language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-api-user
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user fchara/udagram-api-user:latest
  - cd ../udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed fchara/udagram-api-feed:latest
  - cd ../udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend fchara/udagram-frontend:latest
  - cd ../udagram-reverseproxy
  - docker build -t reverseproxy .
  - docker tag reverseproxy fchara/reverseproxy:latest
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fchara/udagram-api-user
  - docker push fchara/udagram-api-feed
  - docker push fchara/udagram-frontend
  - docker push fchara/reverseproxy
